plugins {
    id 'base'
}

ext {
    springAiVersion = '1.1.8'
    springBootVersion = '3.5.15'
}

allprojects {
    group = 'io.github.lyx9527'
    version = '1.0.0-SNAPSHOT'

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'maven-publish'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
        withSourcesJar()
    }

    dependencies {
        api platform("org.springframework.boot:spring-boot-dependencies:${springBootVersion}")
        api platform("org.springframework.ai:spring-ai-bom:${springAiVersion}")
        annotationProcessor platform("org.springframework.boot:spring-boot-dependencies:${springBootVersion}")
        testImplementation platform("org.springframework.boot:spring-boot-dependencies:${springBootVersion}")
        testImplementation 'org.junit.jupiter:junit-jupiter'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.compilerArgs += ['-parameters']
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }

    publishing {
        publications {
            mavenJava(MavenPublication) {
                from components.java
            }
        }
    }
}
